AoC/urls.py
from django.urls import path
from . import views

app_name = 'AoC'

urlpatterns = [
    path('',                            views.index,  name = 'index'),
    path('solve/<str:question_id>/',    views.solve,  name = 'solve'),
    path('result/<str:question_id>/',   views.result, name = 'result'),
]

AoCProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AoC.urls')),
]

AoC/models.py
from django.db import models

AoC/views.py
from django.shortcuts import render
import os
import importlib.util


""" Returns str of long solution title

Takes the id in the form x_y and returns in the form Day x - Part y
This is makes the id easier to interpret by the user
"""
def id_to_name(id):
    return (
        "Day "      + id.split("_")[0] + 
        " - Part "  + id.split("_")[1] )


# ~~~ RENDER METHODS ~~~

def index(request):
    solution_files_list = []

    for file_name in os.listdir("./AoC/solutions"):
        if file_name.endswith(".py"):
            # extract just the x_y part of task_x_y.py
            solution_files_list.append(file_name[5:8])

    solution_files_list.sort()

    context = {
        "solution_files_list" : solution_files_list,
    }

    return render(request, "AoC/index.html", context)

def solve(request, question_id):
    context = {
        "question_id": question_id,
        "question_title" : id_to_name(question_id),
    }

    return render(request, "AoC/solve.html", context)

def result(request, question_id):
    context = {
        "question_title" : id_to_name(question_id),
    }  
    
    input_string = request.POST.get('input_textbox')

    # Dynamically fetch the correct task and import it as task then execute solve
    try:
        spec = importlib.util.spec_from_file_location("task", "AoC/solutions/task_" + question_id + ".py")
        task = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(task)
        context["result_value"] =  task.solve(input_string) 
    except Exception as e :
        context["result_value"] = "There was an issue. " + str(e)

    return render(request, "AoC/result.html", context)

AoC/templates/AoC/base.html
<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="Solver for Advent Of Code 2020 challenges">
    <meta name="author" content="Fredrik Eglese">
    
    <title>AoC 2020 Solver</title>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>

<body>
    
    <header>
        <div class="navbar navbar-dark bg-dark shadow-sm">
            <div class="container d-flex justify-content-between">
              <a href="{% url 'AoC:index' %}" class="navbar-brand d-flex align-items-center">
                <strong>Advent of Code 2019 Solver</strong>
              </a>
            </div>
          </div>
    </header>

    <!-- Content Goes here -->
    <main role="main">
        <div class="bg-light">
            {% block body %}

            {% endblock %}
        </div>
    </main>

    <footer class="text-muted">
        <div class="container pt-3">           
            <p>This code is work in progress and is just an example of my use of Python3, Django, <a href="https://getbootstrap.com/">Bootstrap</a> and general webdev / programming skills. For more code examples please visit my <a href="https://www.github.com/FredrikEglese">GitHub Page</a>.</p>
        </div>
    </footer>

</body>
</html>

AoC/templates/AoC/index.html
{% extends 'AoC/base.html' %}

{% block body %}
    <section class="jumbotron text-center">
        <div class="container">
            <h1>Automatic solutions for AoC</h1>
            <p class="lead text-muted">Solutions to some of the AoC challenges for 2020. Written by <a href="https://www.github.com/FredrikEglese">Fredrik Eglese</a>.</p>  
        </div>
    </section>

    <section>
        {% if solution_files_list %}

            <div class="album py-5 bg-light">
                <div class="container">
                    <div class="row">

                    {% for avaliable_solution in solution_files_list %}

                        <div class="col-md-4">
                            <div class="card mb-4 shadow-sm">
                                <div class="card-body">
                                    <p class="card-text"> Day {{ avaliable_solution.0 }} - Part {{ avaliable_solution.2 }} </p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <a href="{% url 'AoC:solve' avaliable_solution%}">
                                                <button type="button" class="btn btn-sm btn-outline-secondary">Solver</button>
                                            </a>
                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    {% endfor %}

                    </div>
                </div>
            </div>
                
        {% else %}
        
            <div class="container pb-2">
                <h4 class="text-center">No solvers avaliable. Please check that Python files are in the correct directory.</h4>
            </div>
        
        {% endif %}
    
    </section>

{% endblock %}

AoC/templates/AoC/result.html
{% extends 'AoC/base.html' %}

{% block body %}

    <div class="container pb-2">

        <section class="text-center pt-3">
            <h1>Result for: {{question_title}}</h1>
        </section>

        <section class="text-center pt-3">
            <h3> {{result_value}} </h3>
        </section>
    
    </div>
{% endblock %}

AoC/templates/AoC/solve.html
{% extends 'AoC/base.html' %}

{% block body %}

    <div class="container pb-2">

        <section class="text-center pt-3">
            <h1>Solution for: {{question_title}}</h1>
        </section>

        <div class="container">
            <form action="{% url 'AoC:result' question_id %}" method="POST"> {% csrf_token %}
                <div class="form-group">
                    <label for="userInput">Task Input (As provided from AoC website):</label>
                    <textarea class="form-control" name="input_textbox" rows="10"></textarea>
                </div>

                <div>
                    <input type="submit" value="Solve" class="btn btn-block btn-primary mb-2" />
                </div>
            </form> 
        </div>
        
    </div>
    
{% endblock %}